# SEO tag
title: Wojciech Wnętrzak
description: Ruby & JavaScript development
url: "https://urizen.pl"
twitter:
  username: morgoth85
  card: summary
social:
  name: Wojciech Wnętrzak
  links:
    - https://twitter.com/morgoth85
    - https://www.linkedin.com/in/wojciech-wnetrzak-a8403918a
    - https://github.com/morgoth

email: "contact@urizen.pl"
baseurl: "" #name of GitHub repository

# Markdown
highlighter: rouge
markdown: kramdown

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-email-protect
