# SEO tag
title: Wojciech Wnętrzak
description: Ruby & JavaScript engineering
url: "https://wnetrzak.pl"
twitter:
  username: morgoth85
  card: summary
social:
  name: Wojciech Wnętrzak
  links:
    - https://twitter.com/morgoth85
    - https://www.linkedin.com/in/wojciech-wnetrzak-a8403918a
    - https://github.com/morgoth

email: "contact@wnetrzak.pl"
baseurl: "" #name of GitHub repository

# Markdown
highlighter: rouge
markdown: kramdown

include:
  - _pages

exclude:
  - README.md

plugins:
  - jekyll-seo-tag
