source "https://rubygems.org"

# gem "coffee-script"
gem "haml"
gem "compass"
gem "tilt", git: "git://github.com/rtomayko/tilt.git", branch: "encodings"
# gem "rack"
gem "rake-pipeline", git: "git://github.com/livingsocial/rake-pipeline.git"
gem "rake-pipeline-web-filters", git: "git://github.com/wycats/rake-pipeline-web-filters.git"
# gem "ruby-debug19", require: "ruby-debug"
